<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function itkdev_openid_connect_drupal_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  Drupal::service('itkdev_openid_connect_drupal.form_helper')->alterForm($form, $form_state, $form_id);
}

/**
 * Implements hook_user_default_page_login_ignore_whitelist_alter().
 */
function itkdev_openid_connect_drupal_user_default_page_login_ignore_whitelist_alter(array &$ignored_routes) {
  // @todo We should check if we have a location request before ignoring our route.
  $ignored_routes[] = 'itkdev_openid_connect_drupal.openid_connect';
}
